sudo: false
install: git clone --depth 1 https://github.com/sstephenson/bats.git
script: make test
language: c
env:
  - SHENV_NATIVE_EXT=
  - SHENV_NATIVE_EXT=1
notifications:
  email:
    on_success: never

